#!/usr/bin/env bash

export DNS_HELPER_VERSION=1.0.2

export DNS_HELPER_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
export DNS_HELPER_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

show_help() {
    echo "DNS Helper v$DNS_HELPER_VERSION"
    echo "Usage: dns-helper [COMMAND] [OPTIONS]"
    echo
    echo "COMMANDS:"
    echo "  nameserver <domain>          Display the nameserver of a domain."
    echo "  record <domain> <type>       Display a specific record of a domain."
    echo "  records <domain> [<records>] [options]   Display common records of a domain."
    echo "  zone-file <domain> [<records>] [options] Display records in zone file format."
    echo "  update                       Update the script to the latest version."
    echo "  version                      Display the script version."
    echo
    echo "OPTIONS:"
    echo "  -h, --help                  Display this help message."
    echo "  --resolver=<IP>             Specify the DNS server to use (default: 8.8.8.8)."
    echo
    echo "COMMAND ARGUMENTS:"
    echo "  nameserver:"
    echo "    <domain>                  The domain for which to display the nameserver."
    echo
    echo "  record:"
    echo "    <domain>                  The domain for which to display a specific record."
    echo "    [<type>, [<type>, ...]]   The type of record to display (e.g., A, CNAME, MX, TXT) (default: A)."
    echo
    echo "  records:"
    echo "    <domain>                  The domain for which to display common records."
    echo "    [records]      Additional records to display (e.g., www:CNAME,mail:A)."
    echo "    [options]:"
    echo "      --common-records Include common records when \"records\" is provided."
    echo "      --cpanel-records Include cPanel-specific records when displaying common records."
    echo "      --locaweb-records Include Locaweb-specific records when displaying common records"
    echo "      --cname-and-a Include CNAME and A records when displaying common records."
    echo "      --cname-if-exists Include CNAME record if it exists or A record otherwise when displaying common records."
    echo
    echo "  zone-file:"
    echo "    <domain>                  The domain for which to display records in zone file format."
    echo "    [records]      Additional records to display (e.g., www:CNAME,mail:A)."
    echo "    [options]:"
    echo "      --common-records Include common records when \"records\" is provided."
    echo "      --cpanel-records Include cPanel-specific records when displaying common records."
    echo "      --locaweb-records Include Locaweb-specific records when displaying common records"
    echo "      --cname-and-a Include CNAME and A records when displaying common records."
    echo "      --cname-if-exists Include CNAME record if it exists or A record otherwise when displaying common records."
    echo
    echo "Examples:"
    echo "  dns-helper nameserver example.com"
    echo "  dns-helper --resolver=1.1.1.1 records example.com"
    echo "  dns-helper record example.com A"
    echo "  dns-helper record example.com A MX TXT"
    echo "  dns-helper records example.com --cpanel-records"
    echo "  dns-helper records example.com \"custom:CNAME,custom2:TXT\""
    echo "  dns-helper zone-file example.com --cpanel-records"
    echo "  dns-helper update"
    echo "  dns-helper version"

    exit 0
}

try_get_record() {
    local domain="$1"
    domain="$(echo "$domain" | sed -E "s|\.$||g")"
    local type="${2:-A}"
    type="${type^^}"
    local zone_file_format="$3"

    local cname_and_a=""
    local cname_if_exists=""
    if [[ "$type" == "CNAME-AND-A" ]]; then
        cname_and_a="yes"
        type="A"
    elif [[ "$type" == "CNAME-OR-A" ]]; then
        cname_if_exists="yes"
        type="A"
    fi

    # Get all records
    local subdomain_data
    mapfile -t subdomain_data < <(LANG=en_US.UTF-8; host -4 -t "$type" "$domain" "$DNS_RESOLVER" | tail -n +6 | grep -Eiv "(has no $type record|not found)")

    # Check if CNAME exists
    if [[ "$cname_if_exists" == "yes" && "${subdomain_data[*]}" =~ ( is an alias for ) ]]; then
        type="CNAME"
    fi

    for ln in "${subdomain_data[@]}"; do
        # When a CNAME type is found, the record is returned as "CNAME" and "A" version
        # If the desired type is "A," the CNAME is ignored
        if [[ "$type" == "A" && "$cname_and_a" != "yes" && "$ln" =~ ( is an alias for ) ]]; then
            continue
        fi

        local destination=""
        if [[ "$type" == "MX" && "$ln" =~ ( is handled by ) ]]; then
            # MX format
            destination="$(echo "$ln" | awk '{print $6" "$7}')"
        elif [[ "$type" == "CNAME" && "$ln" =~ ( is an alias for ) ]] \
            || [[ "$type" == "A" && "$cname_and_a" == "yes" && "$ln" =~ ( is an alias for ) ]]; then
            # CNAME format
            destination="$(echo "$ln" | awk '{print $6}')"
        elif [[ "$type" == "TXT" && "$ln" =~ ( descriptive text ) ]]; then
            # TXT format
            destination="$(echo "$ln" | awk '{$1=$2=$3=""; print $0}' | sed -E "s/(^\s*\"|\"$)//g")"
            if [[ "$zone_file_format" == "yes" ]]; then
                destination="\"${destination}\""
            fi
        elif [[ "$type" == "NS" && "$ln" =~ ( name server ) ]]; then
            # Name server format
            destination="$(echo "$ln" | awk '{print $4}')"
        elif [[ "$type" == "A" && "$ln" =~ ( has address ) ]]; then
            # A format
            destination="$(echo "$ln" | awk '{print $4}')"
        elif [[ "$type" == "AAAA" && "$ln" =~ ( has address ) ]]; then
            # AAAA format
            destination="$(echo "$ln" | awk '{print $5}')"
        elif [[ "$type" == "CAA" && "$ln" =~ ( has CAA record ) ]]; then
            # CAA format
            destination="$(echo "$ln" | awk '{$1=$2=$3=$4=""; print $0}')"
        else
            continue
        fi

        # Remove leading and trailing spaces
        destination="$(echo "$destination" | sed -E "s/(^\s+|\s+$)//g")"

        if [[ -n "$destination" ]]; then
            if [[ "$zone_file_format" == "yes" ]]; then
                response="${domain}.\t1\tIN\t${type}\t${destination}"
            else
                response="${domain}\t${type}\t${destination}"
            fi

            echo -e "$response"
        fi
    done
}

show_domain_nameserver() {
    local domain="$1"
    domain="$(echo "$domain" | sed -E "s|\.$||g")"

    if [[ -z "$domain" ]]; then
        echo "Provide the domain." >&2
        exit 1
    fi

    local domain_ns
    domain_ns="$(LANG=en_US.UTF-8; host -t ns "$domain" "$DNS_RESOLVER" | tail -n +6 | grep " name server ")"

    # Couldn't obtain the domain's nameserver
    if [[ -z "$domain_ns" ]]; then
        echo "Couldn't obtain the domain's nameserver." >&2
        exit 2
    fi

    echo "$domain_ns" | awk '{print $4}' | sed -E "s|\.$||g"
}

show_records() {
    local output_format="${1:?Provide the output format.}"
    shift
    local command_args=("$@")

    local cname_and_a=""
    local cname_if_exists=""
    local include_common_records=""
    local include_cpanel_records=""
    local include_locaweb_records=""
    extract_arg command_args "--cname-and-a" cname_and_a "yes"
    extract_arg command_args "--cname-if-exists" cname_if_exists "yes"
    extract_arg command_args "--common-records" include_common_records "yes"
    extract_arg command_args "--cpanel-records" include_cpanel_records "yes"
    extract_arg command_args "--locaweb-records" include_locaweb_records "yes"

    local domain="${command_args[0]}"
    domain="$(echo "$domain" | sed -E "s|\.$||g")"
    local additional_records="${command_args[1]}"

    local zone_file_format=""
    if [[ "$output_format" == "zone-file-format" ]]; then
        zone_file_format="yes"
    fi

    if [[ -z "$additional_records" || "$include_cpanel_records" == "yes" || "$include_locaweb_records" == "yes" ]]; then
        include_common_records="yes"
    fi

    if [[ -z "$domain" ]]; then
        echo "Provide the domain." >&2
        exit 1
    fi

    local default_type="A"
    if [[ "$cname_and_a" == "yes" ]]; then
        default_type="CNAME-AND-A"
    elif [[ "$cname_if_exists" == "yes" ]]; then
        default_type="CNAME-OR-A"
    fi

    local records=()

    # Common records
    if [[ "$include_common_records" == "yes" ]]; then
        local records+=(
            "@:NS"
            "@:${default_type}"
            "www:${default_type}"
            "ftp:${default_type}"
            "mail:${default_type}"
            "smtp:${default_type}"
            "pop:${default_type}"
            "pop3:${default_type}"
            "imap:${default_type}"
            "webmail:${default_type}"
            "autodiscover:CNAME"
            "@:MX"
            "@:TXT"
            "@:CAA"
            "_dmarc:TXT"
            "_domainkey:TXT"
            "mail._domainkey:TXT"
            "default._domainkey:TXT"
            "_acme-challenge:TXT"
            "_acme-challenge.www:TXT"
        )
    fi

    # Localweb records
    if [[ "$include_locaweb_records" == "yes" ]]; then
        records+=(
            "calendario:CNAME"
            "gerenciador:CNAME"
            "relatorio:CNAME"
            "relatorios:CNAME"
            "painel:CNAME"
            "mobile:CNAME"
            "pda:CNAME"
            "ns1:CNAME"
            "ns2:CNAME"
            "ns3:CNAME"
        )
    fi

   # cPanel records
    if [[ "$include_cpanel_records" == "yes" ]]; then
        records+=(
            "webdisk:${default_type}"
            "cpcalendars:${default_type}"
            "cpanel:${default_type}"
            "whm:${default_type}"
            "cpcontacts:${default_type}"
            "_caldav._tcp:TXT"
            "_caldavs._tcp:TXT"
            "_carddav._tcp:TXT"
            "_carddavs._tcp:TXT"
            "_cpanel-dcv-test-record:TXT"
        )
    fi

    if [[ "$zone_file_format" == "yes" ]]; then
        echo ";; Domain:     ${domain}."
    fi

    if [[ -n "$additional_records" ]]; then
        local additional_records_arr
        IFS=',' read -ra additional_records_arr <<< "$additional_records"
        records+=("${additional_records_arr[@]}")
    fi

    local record_name record_type
    for record in "${records[@]}"; do
        if [[ -z "$record" ]]; then
            continue
        fi

        if ! [[ "$record" =~ \: ]]; then
            record="$record:${default_type}"
        fi

        record_name="$(echo "$record" | awk -F ":" '{print $1}' | sed -E "s|\.$||g" | sed -E "s|@|$domain|g")"
        record_type="$(echo "$record" | awk -F ":" '{print $2}')"

        if [[ "$record_name" != "$domain" ]] && ! [[ "$record_name" =~ (\.${domain}$) ]]; then
            record_name="${record_name}.${domain}"
        fi

        try_get_record "$record_name" "$record_type" "$zone_file_format"
    done
}

show_record() {
    local domain="$1"
    domain="$(echo "$domain" | sed -E "s|\.$||g")"
    shift
    local types=("$@")

    if [[ -z "${types[*]}" ]]; then
        types=("A")
    fi

    local type
    for type in "${types[@]}"; do
        try_get_record "$domain" "$type"
    done
}

extract_arg() {
    local -n all_args_ref="$1"
    local arg_name="$2"
    local -n output_var_ref="$3"
    local remove_if_exists="${4:-no}"

    if [[ -z "$arg_name" ]]; then
        return
    fi

    local final_args=()
    local remove_from_args
    for arg in "${all_args_ref[@]}"; do
        remove_from_args=""

        if [[ -n "$arg" ]]; then
            if [[ "$arg" =~ (^${arg_name}=) ]]; then
                output_var_ref="$(echo "$arg" | sed -En "s|^${arg_name}=[\"']?(.*)[\"']?|\1|p")"
                remove_from_args="$remove_if_exists"
            elif [[ "$arg" =~ (^${arg_name}$) ]]; then
                output_var_ref="yes"
                remove_from_args="$remove_if_exists"
            fi
        fi

        # Remove custom arguments to avoid errors when passing the command to docker
        if [[ "$remove_from_args" != "yes" ]]; then
            final_args+=("$arg")
        fi
    done

    # Update the argument list
    if [[ "${remove_if_exists,,}" == "yes" ]]; then
        all_args_ref=("${final_args[@]}")
    fi
}

export DNS_RESOLVER="8.8.8.8"
export COMMAND=""
export args=("$@")

extract_arg args "--resolver" DNS_RESOLVER "yes"
if [[ -n "${args[0]}" ]]; then
    COMMAND="${args[0]}"
    args=("${args[@]:1}")
fi

case "$COMMAND" in
help|--help|-h)
    show_help
    ;;

nameserver)
    # Show the domain's nameserver
    # Parameters: <domain>
    show_domain_nameserver "${args[@]}"
    ;;

record)
    # Show a specific record
    # Parameters: <domain> [<type>, [<type>, ...]]
    show_record "${args[@]}"
    ;;

records)
    # Show records commonly used by domains
    # Parameters: <domain> [<records(Ex: "ftp,www:CNAME,mail:A")>] [--cpanel-records]
    show_records "plain" "${args[@]}"
    ;;

zone-file)
    # Show records commonly used by domains in zone file format
    # Parameters: <domain> [<records(Ex: "www:CNAME,mail:A")>] [--cpanel-records]
    show_records "zone-file-format" "${args[@]}"
    ;;

update)
    # Update the script
    curl -L "https://raw.githubusercontent.com/jhmaverick/dns-helper/master/dns-helper" -o "$DNS_HELPER_PATH"
    chmod +x "$DNS_HELPER_PATH"
    exit 0
    ;;

version|--version|-v)
    # Show the script version
    echo "Version $DOCKER_HELPER_VERSION"
    exit 0
    ;;

*)
    echo "Command not found"
    echo
    show_help
    ;;
esac
